# Generated by Django 5.2.1 on 2026-09-29 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('is_food', models.BooleanField(null=True)),
                ('food_group', models.CharField(blank=True, max_length=30)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('feature_version', models.CharField(blank=True, max_length=10)),
                ('extraction_model', models.CharField(blank=True, max_length=50)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='siksha', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('meal', models.CharField(choices=[('BR', '아침'), ('LU', '점심'), ('DN', '저녁')], max_length=2)),
                ('raw_name', models.CharField(max_length=500)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('no_meat', models.BooleanField(default=False)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menus.food')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.restaurant')),
            ],
            options={
                'ordering': ['date', 'meal', 'restaurant__name'],
                'constraints': [models.UniqueConstraint(fields=('date', 'meal', 'restaurant', 'raw_name'), name='unique_menu_item_per_meal')],
            },
        ),
    ]
